### PR TITLE
Add seeding capabilities.

### PR DESCRIPTION
**Pull request by rolftimmermans**
This PR adds the a seeding option to choma. Without explicit seed it will auto generate a seed and report it back to the user. An explicit seed can be passed with the `SEED` environment variable.

Seeding tests allows for much easier debugging of a errors caused by tests running in a particular sequence.

To facilitate this, the `shuffle` function was adapted from lodash to use a seeded prng from the https://github.com/davidbau/seedrandom package.

The seed itself is generated on demand with the default random function.

It could be worth arguing that `Math.random()` should be overridden to also use the same seed so that the complete test suite (if it uses `Math.random()`) is deterministic, but that is probably outside the scope of this PR.

Also added is a "test test" suite that can be run with choma itself. Makes it fairly easy to spot any errors or strange behaviour.

I realize this is a complete overhaul of this library but I'm certain that this is useful for many people.

### CODE REVIEW

**Comment by lennym** [comment]
Thanks for the PR @rolftimmermans, I really appreciate it.

I'll try to take a look at the code asap, but the ideas seem like really good ones, so I'm certainly in favour of merging.

**Comment by lennym** [comment]
This looks good. There's a few things I'd like to change and add, but I'm happy to do that myself (or of course you'd be very welcome to continue to contribute if you're happy to).

* Investigate using a command line flag for the seed in place of an environment variable. If sticking with an env var, the make it a bit more specific. Generic environment variable names like `SEED` have a tendency to end up being unknowingly and inadvertently present on certain systems, and so cause unexpected results.
* Improve the docs to explain the seed thing
* Look at saving the seed in a tmp file so that rather than having to explicitly set it, you could use a "use the same seed as last time" option.

Having said all this, I think what you've done is an improvement on what's there now, so I'll happily merge.

**Comment by lennym** [comment]
Thanks for your contribution @rolftimmermans! 💟

**Comment by lennym** [comment]
Oh wait, you removed all my semi-colons and replaced my single quotes with doubles. We might actually have to be mortal enemies now 😉

**Comment by rolftimmermans** [comment]
> Investigate using a command line flag for the seed in place of an environment variable. If sticking with an env var, the make it a bit more specific. Generic environment variable names like SEED have a tendency to end up being unknowingly and inadvertently present on certain systems, and so cause unexpected results.

I would like that, but how can we pass this easily around if you're using npm, yarn, make or whatever tool to invoke mocha indirectly? I don't think there is a single solution here, what do you think?

I can agree on the generic env var name. What about `MOCHA_SEED` (or maybe `CHOMA_SEED`)?

> Improve the docs to explain the seed thing

I will take care of that once we settle on a name.

> Look at saving the seed in a tmp file so that rather than having to explicitly set it, you could use a "use the same seed as last time" option.

That would be a nice addition!

**Comment by lennym** [comment]
I settled on `CHOMA_SEED`, spruced up the docs a little, and published at `v1.2.0`

I'll take a look at the cli flag and tmp file options for a next release.

Thanks again for contributing.

**Pull request merged**
